// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.15.8
// source: internal/grpc/ephemeralpeer.proto

package grpc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type EphemeralPeerRequestV1 struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	WgParentPubkey        []byte                `protobuf:"bytes,1,opt,name=wg_parent_pubkey,json=wgParentPubkey,proto3" json:"wg_parent_pubkey,omitempty"`
	WgEphemeralPeerPubkey []byte                `protobuf:"bytes,2,opt,name=wg_ephemeral_peer_pubkey,json=wgEphemeralPeerPubkey,proto3" json:"wg_ephemeral_peer_pubkey,omitempty"`
	PostQuantum           *PostQuantumRequestV1 `protobuf:"bytes,3,opt,name=post_quantum,json=postQuantum,proto3" json:"post_quantum,omitempty"`
	Daita                 *DaitaRequestV1       `protobuf:"bytes,4,opt,name=daita,proto3" json:"daita,omitempty"`
}

func (x *EphemeralPeerRequestV1) Reset() {
	*x = EphemeralPeerRequestV1{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_grpc_ephemeralpeer_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EphemeralPeerRequestV1) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EphemeralPeerRequestV1) ProtoMessage() {}

func (x *EphemeralPeerRequestV1) ProtoReflect() protoreflect.Message {
	mi := &file_internal_grpc_ephemeralpeer_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EphemeralPeerRequestV1.ProtoReflect.Descriptor instead.
func (*EphemeralPeerRequestV1) Descriptor() ([]byte, []int) {
	return file_internal_grpc_ephemeralpeer_proto_rawDescGZIP(), []int{0}
}

func (x *EphemeralPeerRequestV1) GetWgParentPubkey() []byte {
	if x != nil {
		return x.WgParentPubkey
	}
	return nil
}

func (x *EphemeralPeerRequestV1) GetWgEphemeralPeerPubkey() []byte {
	if x != nil {
		return x.WgEphemeralPeerPubkey
	}
	return nil
}

func (x *EphemeralPeerRequestV1) GetPostQuantum() *PostQuantumRequestV1 {
	if x != nil {
		return x.PostQuantum
	}
	return nil
}

func (x *EphemeralPeerRequestV1) GetDaita() *DaitaRequestV1 {
	if x != nil {
		return x.Daita
	}
	return nil
}

type PostQuantumRequestV1 struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	KemPubkeys []*KemPubkeyV1 `protobuf:"bytes,1,rep,name=kem_pubkeys,json=kemPubkeys,proto3" json:"kem_pubkeys,omitempty"`
}

func (x *PostQuantumRequestV1) Reset() {
	*x = PostQuantumRequestV1{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_grpc_ephemeralpeer_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PostQuantumRequestV1) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PostQuantumRequestV1) ProtoMessage() {}

func (x *PostQuantumRequestV1) ProtoReflect() protoreflect.Message {
	mi := &file_internal_grpc_ephemeralpeer_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PostQuantumRequestV1.ProtoReflect.Descriptor instead.
func (*PostQuantumRequestV1) Descriptor() ([]byte, []int) {
	return file_internal_grpc_ephemeralpeer_proto_rawDescGZIP(), []int{1}
}

func (x *PostQuantumRequestV1) GetKemPubkeys() []*KemPubkeyV1 {
	if x != nil {
		return x.KemPubkeys
	}
	return nil
}

type KemPubkeyV1 struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AlgorithmName string `protobuf:"bytes,1,opt,name=algorithm_name,json=algorithmName,proto3" json:"algorithm_name,omitempty"`
	KeyData       []byte `protobuf:"bytes,2,opt,name=key_data,json=keyData,proto3" json:"key_data,omitempty"`
}

func (x *KemPubkeyV1) Reset() {
	*x = KemPubkeyV1{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_grpc_ephemeralpeer_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *KemPubkeyV1) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KemPubkeyV1) ProtoMessage() {}

func (x *KemPubkeyV1) ProtoReflect() protoreflect.Message {
	mi := &file_internal_grpc_ephemeralpeer_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KemPubkeyV1.ProtoReflect.Descriptor instead.
func (*KemPubkeyV1) Descriptor() ([]byte, []int) {
	return file_internal_grpc_ephemeralpeer_proto_rawDescGZIP(), []int{2}
}

func (x *KemPubkeyV1) GetAlgorithmName() string {
	if x != nil {
		return x.AlgorithmName
	}
	return ""
}

func (x *KemPubkeyV1) GetKeyData() []byte {
	if x != nil {
		return x.KeyData
	}
	return nil
}

type DaitaRequestV1 struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ActivateDaita bool `protobuf:"varint,1,opt,name=activate_daita,json=activateDaita,proto3" json:"activate_daita,omitempty"`
}

func (x *DaitaRequestV1) Reset() {
	*x = DaitaRequestV1{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_grpc_ephemeralpeer_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DaitaRequestV1) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DaitaRequestV1) ProtoMessage() {}

func (x *DaitaRequestV1) ProtoReflect() protoreflect.Message {
	mi := &file_internal_grpc_ephemeralpeer_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DaitaRequestV1.ProtoReflect.Descriptor instead.
func (*DaitaRequestV1) Descriptor() ([]byte, []int) {
	return file_internal_grpc_ephemeralpeer_proto_rawDescGZIP(), []int{3}
}

func (x *DaitaRequestV1) GetActivateDaita() bool {
	if x != nil {
		return x.ActivateDaita
	}
	return false
}

type EphemeralPeerResponseV1 struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PostQuantum *PostQuantumResponseV1 `protobuf:"bytes,1,opt,name=post_quantum,json=postQuantum,proto3" json:"post_quantum,omitempty"`
}

func (x *EphemeralPeerResponseV1) Reset() {
	*x = EphemeralPeerResponseV1{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_grpc_ephemeralpeer_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EphemeralPeerResponseV1) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EphemeralPeerResponseV1) ProtoMessage() {}

func (x *EphemeralPeerResponseV1) ProtoReflect() protoreflect.Message {
	mi := &file_internal_grpc_ephemeralpeer_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EphemeralPeerResponseV1.ProtoReflect.Descriptor instead.
func (*EphemeralPeerResponseV1) Descriptor() ([]byte, []int) {
	return file_internal_grpc_ephemeralpeer_proto_rawDescGZIP(), []int{4}
}

func (x *EphemeralPeerResponseV1) GetPostQuantum() *PostQuantumResponseV1 {
	if x != nil {
		return x.PostQuantum
	}
	return nil
}

type PostQuantumResponseV1 struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ciphertexts [][]byte `protobuf:"bytes,1,rep,name=ciphertexts,proto3" json:"ciphertexts,omitempty"`
}

func (x *PostQuantumResponseV1) Reset() {
	*x = PostQuantumResponseV1{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_grpc_ephemeralpeer_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PostQuantumResponseV1) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PostQuantumResponseV1) ProtoMessage() {}

func (x *PostQuantumResponseV1) ProtoReflect() protoreflect.Message {
	mi := &file_internal_grpc_ephemeralpeer_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PostQuantumResponseV1.ProtoReflect.Descriptor instead.
func (*PostQuantumResponseV1) Descriptor() ([]byte, []int) {
	return file_internal_grpc_ephemeralpeer_proto_rawDescGZIP(), []int{5}
}

func (x *PostQuantumResponseV1) GetCiphertexts() [][]byte {
	if x != nil {
		return x.Ciphertexts
	}
	return nil
}

var File_internal_grpc_ephemeralpeer_proto protoreflect.FileDescriptor

var file_internal_grpc_ephemeralpeer_proto_rawDesc = []byte{
	0x0a, 0x21, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x2f, 0x67, 0x72, 0x70, 0x63, 0x2f,
	0x65, 0x70, 0x68, 0x65, 0x6d, 0x65, 0x72, 0x61, 0x6c, 0x70, 0x65, 0x65, 0x72, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x12, 0x0d, 0x65, 0x70, 0x68, 0x65, 0x6d, 0x65, 0x72, 0x61, 0x6c, 0x70, 0x65,
	0x65, 0x72, 0x22, 0xf8, 0x01, 0x0a, 0x16, 0x45, 0x70, 0x68, 0x65, 0x6d, 0x65, 0x72, 0x61, 0x6c,
	0x50, 0x65, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x56, 0x31, 0x12, 0x28, 0x0a,
	0x10, 0x77, 0x67, 0x5f, 0x70, 0x61, 0x72, 0x65, 0x6e, 0x74, 0x5f, 0x70, 0x75, 0x62, 0x6b, 0x65,
	0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x0e, 0x77, 0x67, 0x50, 0x61, 0x72, 0x65, 0x6e,
	0x74, 0x50, 0x75, 0x62, 0x6b, 0x65, 0x79, 0x12, 0x37, 0x0a, 0x18, 0x77, 0x67, 0x5f, 0x65, 0x70,
	0x68, 0x65, 0x6d, 0x65, 0x72, 0x61, 0x6c, 0x5f, 0x70, 0x65, 0x65, 0x72, 0x5f, 0x70, 0x75, 0x62,
	0x6b, 0x65, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x15, 0x77, 0x67, 0x45, 0x70, 0x68,
	0x65, 0x6d, 0x65, 0x72, 0x61, 0x6c, 0x50, 0x65, 0x65, 0x72, 0x50, 0x75, 0x62, 0x6b, 0x65, 0x79,
	0x12, 0x46, 0x0a, 0x0c, 0x70, 0x6f, 0x73, 0x74, 0x5f, 0x71, 0x75, 0x61, 0x6e, 0x74, 0x75, 0x6d,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x23, 0x2e, 0x65, 0x70, 0x68, 0x65, 0x6d, 0x65, 0x72,
	0x61, 0x6c, 0x70, 0x65, 0x65, 0x72, 0x2e, 0x50, 0x6f, 0x73, 0x74, 0x51, 0x75, 0x61, 0x6e, 0x74,
	0x75, 0x6d, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x56, 0x31, 0x52, 0x0b, 0x70, 0x6f, 0x73,
	0x74, 0x51, 0x75, 0x61, 0x6e, 0x74, 0x75, 0x6d, 0x12, 0x33, 0x0a, 0x05, 0x64, 0x61, 0x69, 0x74,
	0x61, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1d, 0x2e, 0x65, 0x70, 0x68, 0x65, 0x6d, 0x65,
	0x72, 0x61, 0x6c, 0x70, 0x65, 0x65, 0x72, 0x2e, 0x44, 0x61, 0x69, 0x74, 0x61, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x56, 0x31, 0x52, 0x05, 0x64, 0x61, 0x69, 0x74, 0x61, 0x22, 0x53, 0x0a,
	0x14, 0x50, 0x6f, 0x73, 0x74, 0x51, 0x75, 0x61, 0x6e, 0x74, 0x75, 0x6d, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x56, 0x31, 0x12, 0x3b, 0x0a, 0x0b, 0x6b, 0x65, 0x6d, 0x5f, 0x70, 0x75, 0x62,
	0x6b, 0x65, 0x79, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x65, 0x70, 0x68,
	0x65, 0x6d, 0x65, 0x72, 0x61, 0x6c, 0x70, 0x65, 0x65, 0x72, 0x2e, 0x4b, 0x65, 0x6d, 0x50, 0x75,
	0x62, 0x6b, 0x65, 0x79, 0x56, 0x31, 0x52, 0x0a, 0x6b, 0x65, 0x6d, 0x50, 0x75, 0x62, 0x6b, 0x65,
	0x79, 0x73, 0x22, 0x4f, 0x0a, 0x0b, 0x4b, 0x65, 0x6d, 0x50, 0x75, 0x62, 0x6b, 0x65, 0x79, 0x56,
	0x31, 0x12, 0x25, 0x0a, 0x0e, 0x61, 0x6c, 0x67, 0x6f, 0x72, 0x69, 0x74, 0x68, 0x6d, 0x5f, 0x6e,
	0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0d, 0x61, 0x6c, 0x67, 0x6f, 0x72,
	0x69, 0x74, 0x68, 0x6d, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x19, 0x0a, 0x08, 0x6b, 0x65, 0x79, 0x5f,
	0x64, 0x61, 0x74, 0x61, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x07, 0x6b, 0x65, 0x79, 0x44,
	0x61, 0x74, 0x61, 0x22, 0x37, 0x0a, 0x0e, 0x44, 0x61, 0x69, 0x74, 0x61, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x56, 0x31, 0x12, 0x25, 0x0a, 0x0e, 0x61, 0x63, 0x74, 0x69, 0x76, 0x61, 0x74,
	0x65, 0x5f, 0x64, 0x61, 0x69, 0x74, 0x61, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x0d, 0x61,
	0x63, 0x74, 0x69, 0x76, 0x61, 0x74, 0x65, 0x44, 0x61, 0x69, 0x74, 0x61, 0x22, 0x62, 0x0a, 0x17,
	0x45, 0x70, 0x68, 0x65, 0x6d, 0x65, 0x72, 0x61, 0x6c, 0x50, 0x65, 0x65, 0x72, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x56, 0x31, 0x12, 0x47, 0x0a, 0x0c, 0x70, 0x6f, 0x73, 0x74, 0x5f,
	0x71, 0x75, 0x61, 0x6e, 0x74, 0x75, 0x6d, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x24, 0x2e,
	0x65, 0x70, 0x68, 0x65, 0x6d, 0x65, 0x72, 0x61, 0x6c, 0x70, 0x65, 0x65, 0x72, 0x2e, 0x50, 0x6f,
	0x73, 0x74, 0x51, 0x75, 0x61, 0x6e, 0x74, 0x75, 0x6d, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x56, 0x31, 0x52, 0x0b, 0x70, 0x6f, 0x73, 0x74, 0x51, 0x75, 0x61, 0x6e, 0x74, 0x75, 0x6d,
	0x22, 0x39, 0x0a, 0x15, 0x50, 0x6f, 0x73, 0x74, 0x51, 0x75, 0x61, 0x6e, 0x74, 0x75, 0x6d, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x56, 0x31, 0x12, 0x20, 0x0a, 0x0b, 0x63, 0x69, 0x70,
	0x68, 0x65, 0x72, 0x74, 0x65, 0x78, 0x74, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0c, 0x52, 0x0b,
	0x63, 0x69, 0x70, 0x68, 0x65, 0x72, 0x74, 0x65, 0x78, 0x74, 0x73, 0x32, 0x72, 0x0a, 0x0d, 0x45,
	0x70, 0x68, 0x65, 0x6d, 0x65, 0x72, 0x61, 0x6c, 0x50, 0x65, 0x65, 0x72, 0x12, 0x61, 0x0a, 0x0e,
	0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x50, 0x65, 0x65, 0x72, 0x56, 0x31, 0x12, 0x25,
	0x2e, 0x65, 0x70, 0x68, 0x65, 0x6d, 0x65, 0x72, 0x61, 0x6c, 0x70, 0x65, 0x65, 0x72, 0x2e, 0x45,
	0x70, 0x68, 0x65, 0x6d, 0x65, 0x72, 0x61, 0x6c, 0x50, 0x65, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x56, 0x31, 0x1a, 0x26, 0x2e, 0x65, 0x70, 0x68, 0x65, 0x6d, 0x65, 0x72, 0x61,
	0x6c, 0x70, 0x65, 0x65, 0x72, 0x2e, 0x45, 0x70, 0x68, 0x65, 0x6d, 0x65, 0x72, 0x61, 0x6c, 0x50,
	0x65, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x56, 0x31, 0x22, 0x00, 0x42,
	0x25, 0x5a, 0x23, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x6d, 0x75,
	0x6c, 0x6c, 0x76, 0x61, 0x64, 0x2f, 0x65, 0x70, 0x2f, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61,
	0x6c, 0x2f, 0x67, 0x72, 0x70, 0x63, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_internal_grpc_ephemeralpeer_proto_rawDescOnce sync.Once
	file_internal_grpc_ephemeralpeer_proto_rawDescData = file_internal_grpc_ephemeralpeer_proto_rawDesc
)

func file_internal_grpc_ephemeralpeer_proto_rawDescGZIP() []byte {
	file_internal_grpc_ephemeralpeer_proto_rawDescOnce.Do(func() {
		file_internal_grpc_ephemeralpeer_proto_rawDescData = protoimpl.X.CompressGZIP(file_internal_grpc_ephemeralpeer_proto_rawDescData)
	})
	return file_internal_grpc_ephemeralpeer_proto_rawDescData
}

var file_internal_grpc_ephemeralpeer_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_internal_grpc_ephemeralpeer_proto_goTypes = []interface{}{
	(*EphemeralPeerRequestV1)(nil),  // 0: ephemeralpeer.EphemeralPeerRequestV1
	(*PostQuantumRequestV1)(nil),    // 1: ephemeralpeer.PostQuantumRequestV1
	(*KemPubkeyV1)(nil),             // 2: ephemeralpeer.KemPubkeyV1
	(*DaitaRequestV1)(nil),          // 3: ephemeralpeer.DaitaRequestV1
	(*EphemeralPeerResponseV1)(nil), // 4: ephemeralpeer.EphemeralPeerResponseV1
	(*PostQuantumResponseV1)(nil),   // 5: ephemeralpeer.PostQuantumResponseV1
}
var file_internal_grpc_ephemeralpeer_proto_depIdxs = []int32{
	1, // 0: ephemeralpeer.EphemeralPeerRequestV1.post_quantum:type_name -> ephemeralpeer.PostQuantumRequestV1
	3, // 1: ephemeralpeer.EphemeralPeerRequestV1.daita:type_name -> ephemeralpeer.DaitaRequestV1
	2, // 2: ephemeralpeer.PostQuantumRequestV1.kem_pubkeys:type_name -> ephemeralpeer.KemPubkeyV1
	5, // 3: ephemeralpeer.EphemeralPeerResponseV1.post_quantum:type_name -> ephemeralpeer.PostQuantumResponseV1
	0, // 4: ephemeralpeer.EphemeralPeer.RegisterPeerV1:input_type -> ephemeralpeer.EphemeralPeerRequestV1
	4, // 5: ephemeralpeer.EphemeralPeer.RegisterPeerV1:output_type -> ephemeralpeer.EphemeralPeerResponseV1
	5, // [5:6] is the sub-list for method output_type
	4, // [4:5] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_internal_grpc_ephemeralpeer_proto_init() }
func file_internal_grpc_ephemeralpeer_proto_init() {
	if File_internal_grpc_ephemeralpeer_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_internal_grpc_ephemeralpeer_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EphemeralPeerRequestV1); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_grpc_ephemeralpeer_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PostQuantumRequestV1); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_grpc_ephemeralpeer_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*KemPubkeyV1); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_grpc_ephemeralpeer_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DaitaRequestV1); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_grpc_ephemeralpeer_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EphemeralPeerResponseV1); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_grpc_ephemeralpeer_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PostQuantumResponseV1); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_internal_grpc_ephemeralpeer_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_internal_grpc_ephemeralpeer_proto_goTypes,
		DependencyIndexes: file_internal_grpc_ephemeralpeer_proto_depIdxs,
		MessageInfos:      file_internal_grpc_ephemeralpeer_proto_msgTypes,
	}.Build()
	File_internal_grpc_ephemeralpeer_proto = out.File
	file_internal_grpc_ephemeralpeer_proto_rawDesc = nil
	file_internal_grpc_ephemeralpeer_proto_goTypes = nil
	file_internal_grpc_ephemeralpeer_proto_depIdxs = nil
}
